#端口，对外开放
server:
  port: 10086
#Eureka对外的服务名
spring:
  application:
    name: ly-registy
#默认注册自己，或者注册到其他eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: false #不注册自己
    fetch-registry: false #不拉取服务
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1