server:
  port: 8085
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /leyou
    host: 127.0.0.1
    username: leyou
    password: 521410
  redis:
    host: 127.0.0.1

ly:
  sms:
    accessKeyId: LTAI4FskspNW8VPWPypEHaMg
    accessKeySecret: SSHZpISoai8OBLx9OcVAQYo0uMOYZp
    signName: 商城
    verifyCodeTemplate: verifyCodeTemplate



