server:
  port: 10010

spring:
  application:
    name: api-gateway
 # profiles:
    #include: classpath:application-whitelist.yml
ly:
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api #路由匹配前缀
  routes:
    item-service: /item/**
    user-service: /user/**
    auth-service: /auth/**
    search-service:
      path: /search/**
      serviceId: search-service
      strip-prefix: false
    upload-servive:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false #不去除匹配前缀
  add-host-header: true
  sensitive-headers: # 覆盖默认敏感头信息
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #熔断超时时长

ribbon:
  ConnectTimeout: 1000 #ribbon连接超时时长
  ReadTimeout: 3500 #ribbon读取超时时长
  MaxAutoRetries: 0 #当前服务重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数
