server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/yun6
    username: root
    password: 521410
  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: 521410
    host: 127.0.0.1
  redis:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印mybatis的sql
  #type-aliases-package: com.leyou.user.pojo  # 起别名
ly:
  user:
    sms:
      register:
        exchange: ly.sms.exchange
        routingKey: sms.verify.code
        expiredTime: 5